---
title: "Hopkins-Covid"
output: html_document
---

```{r}
library(stringr)
library(readr)
library(curl)
library(lubridate)
library(dplyr)
library(tidyverse)
library(maps)
library(mapdata)
```


```{r}
url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"
file_names <- c("time_series_covid19_confirmed_global.csv", 
"time_series_covid19_deaths_global.csv", 
"time_series_covid19_confirmed_US.csv", 
"time_series_covid19_deaths_US.csv")
urls <- str_c(url_in,file_names)
global_cases <- read_csv(urls[1])
global_deaths <- read_csv(urls[2])
US_cases <- read_csv(urls[3])
US_deaths <- read_csv(urls[4])
```

```{r}
global_cases <- global_cases %>% 
    pivot_longer(cols = -c('Province/State', 'Country/Region', Lat, Long),
                names_to = "date", values_to = "cases") %>%
    select(-c(Lat, Long))
```

```{r}
global_deaths <- global_deaths %>%
    pivot_longer(cols = -c('Province/State', 'Country/Region',
                           Lat, Long),
                 names_to = "date",
                 values_to = "deaths") %>%
    select(-c(Lat, Long))
```

```{r}
global <- global_cases %>%
  full_join(global_deaths) %>%
  rename(Country_Region = "Country/Region",
         Province_State = "Province/State") %>%
  mutate(date = mdy(date))
```

```{r}
global <- global %>% filter(cases >0)
```

```{r}
US_cases <- US_cases %>%
  pivot_longer(cols = -(UID:Combined_Key),
               names_to = "date",
               values_to = "cases") %>%
  select(Admin2:cases) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long_))
```

```{r}
US_deaths <- US_deaths %>%
  pivot_longer(cols = -(UID:Population),
               names_to = "date",
               values_to = "deaths") %>%
  select(Admin2:deaths) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long_))
```

```{r}
US <- US_cases %>%
  full_join(US_deaths)
```

```{r}
global <- global %>%
  unite("Combined_Key",
        c(Province_State, Country_Region),
        sep = ", ",
        na.rm = TRUE,
        remove = FALSE)
```

```{r}
uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"
uid <- read_csv(uid_lookup_url) %>%
  select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))
```

```{r}
global <- global %>%
  left_join(uid, by = c("Province_State", "Country_Region")) %>%
  select(-c(UID, FIPS)) %>%
  select(Province_State, Country_Region, date,
         cases, deaths, Population,
         Combined_Key)
```

```{r}
US_by_state <- US %>%
  group_by(Province_State, Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths),
            Population = sum(Population)) %>%
  mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
  select(Province_State, Country_Region, date,
         cases, deaths, deaths_per_mill, Population) %>%
  ungroup()
```

```{r}
US_totals <- US_by_state %>%
    group_by(Country_Region, date) %>%
    summarize(cases = sum(cases), deaths = sum(deaths),
                Population = sum(Population)) %>%
    mutate(deaths_per_mill = deaths *1000000 / Population) %>%
    select(Country_Region, date, cases, deaths, deaths_per_mill,
            Population) %>%
    ungroup()
```

```{r}
US_totals %>%
    filter(cases > 0) %>%
    ggplot(aes(x = date, y = cases)) +
    geom_line(aes(color = "cases")) +
    geom_point(aes(color = "cases")) +
    geom_line(aes(y = deaths, color = "deaths")) +
    geom_point(aes(y = deaths, color = "deaths")) +
    scale_y_log10() +
    theme(legend.position = "bottom",
            axis.text.x = element_text(angle = 90)) +
    labs(title = "COVID19 in US", y = NULL)
```

```{r}
US_totals %>%
    filter(cases > 0) %>%
    ggplot(aes(x = date, y = cases)) +
    geom_line(aes(color = "cases")) +
    geom_point(aes(color = "cases")) +
    geom_line(aes(y = deaths, color = "deaths")) +
    geom_point(aes(y = deaths, color = "deaths")) +
    scale_y_log10() +
    theme(legend.position = "bottom",
            axis.text.x = element_text(angle = 90)) +
    labs(title = "COVID19 in US", y = NULL)
```

```{r}
state <- "New York"
US_by_state %>%
    filter(Province_State == state) %>%
    filter(cases >0) %>%
    ggplot(aes(x = date, y = cases)) +
    geom_line(aes(color = "cases")) +
    geom_point(aes(color = "cases")) +
    geom_line(aes(y = deaths, color = "deaths")) +
    geom_point(aes(y = deaths, color = "deaths")) +
    scale_y_log10() +
    theme(legend.position = "bottom",
            axis.text.x = element_text(angle = 90)) +
    labs(title = str_c("COVID19 in ", state), y = NULL)
```

```{r}
US_by_state <- US_by_state %>% 
        mutate(new_cases = cases - lag(cases),
                new_deaths = deaths - lag(deaths))
US_totals <- US_totals %>%
    mutate(new_cases = cases - lag(cases),
            new_deaths = deaths - lag(deaths))
```

```{r}
US_totals %>%
        ggplot(aes(x = date, y = new_cases)) +
        geom_line(aes(color = "new_cases")) +
        geom_point(aes(color = "new_cases")) + 
        geom_line(aes(y = new_deaths, color = "new_deaths")) +
        geom_point(aes(y = new_deaths, color = "new_deaths")) + 
        scale_y_log10() +
        theme(legend.position = "bottom",
                axis.text.x = element_text(angle = 90)) +
        labs(title = "COVID19 in US", y = NULL)
```

```{r}
state <- "New York"
US_by_state %>%
  filter(Province_State == state) %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_line(aes(color = "new_cases")) +
  geom_point(aes(color = "new_cases")) + 
  geom_line(aes(y = new_deaths, color = "new_deaths")) +
  geom_point(aes(y = new_deaths, color = "new_deaths")) + 
  scale_y_log10() +
  theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 90)) +
  labs(title = str_c("COVID19 in ",state), y = NULL)
```

```{r}
US_state_totals <- US_by_state %>%
  group_by(Province_State) %>%
  summarize(deaths = max(deaths), cases = max(cases),
            population = max(Population),
            cases_per_thou = 1000 * cases / population,
            deaths_per_thou = 1000 * deaths / population) %>%
  filter(cases > 0, population > 0)
```



```{r}
US_map <- map_data("state")
US_map$region <- str_to_title(US_map$region)
US_map_state_totals <-US_state_totals %>%
  left_join(., US_map, by = c("Province_State" = "region"))
```

```{r}
ggplot(US_map_state_totals, aes(x = long, y = lat, group = group, 
                                fill = deaths_per_thou)) +
  geom_polygon() +
  scale_fill_gradient(low = "white", high = "green")
```
```{r}
Canada <- filter(global, Country_Region == "Canada")
Canada <- Canada %>%
  group_by(Province_State, Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths),
            Population = sum(Population)) %>%
  mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
  select(Province_State, Country_Region, date,
         cases, deaths, deaths_per_mill, Population) %>%
  ungroup()
Canada <- Canada %>% 
        mutate(new_cases = cases - lag(cases),
                new_deaths = deaths - lag(deaths))
Brittish_Columbia <- filter(Canada, Province_State == "British Columbia")
Washington <- filter(US_by_state, Province_State == "Washington")
```

```{r}
Washington_filtered <- Washington %>% 
  filter(date %in% Brittish_Columbia$date)
Brittish_Columbia_filtered <- Brittish_Columbia %>% 
  filter(date %in% Washington$date)

combined_data <- data.frame(
  date = Washington_filtered$date,
  WA_deaths_per_mill = Washington_filtered$deaths_per_mill,
  BC_deaths_per_mill = Brittish_Columbia_filtered$deaths_per_mill)
ggplot(combined_data, aes(x = date)) +
  geom_line(aes(y = WA_deaths_per_mill, color = "Washington")) +
  geom_line(aes(y = BC_deaths_per_mill, color = "British Columbia")) +
  scale_color_manual(name = "Province/State", values = c("Washington" = "purple", "British Columbia" = "green")) +
  labs(title = "COVID-19 Deaths per Million in Washington State and British Columbia",
       y = "Deaths per Million",
       color = "Neighboring US/Canada Province/State") +
  theme_minimal()

```

